name: "Terraform Integration Tests"
on: [push]

jobs:
  Run-Integration-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: bobbyjameswilliams/terraform-provider-jamfpro/checkout@latest
        with:
          sparse-checkout: |
            tests

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Run Tests
        run: |
          terraform init
          terraform test
